### ISSUE TITLE
Paypal payment method generating error with the Encrypted payments option on the website

### ISSUE THREAD

**Issue by crashzk** [Azuriom/Plugin-Shop#159]
On the Azurim website, I configured it to accept PayPal as a payment method, in this case I configured the email I use on PayPal.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/6b9112e8-bece-4690-87ca-b6b9153fd93d)

In my PayPal account in **Website payment preferences** I have activated the option **Block payment on unencrypted website**

This is where the problem in question begins, as the option to block payment on unencrypted website is activated, it always generates this error when I try to complete the payment.

![image](https://github.com/Azuriom/Plugin-Shop/assets/32937653/5ec5db43-f619-4ee3-8b91-027a475ac284)
**_(An error occurred. Please try again later.)_**

If I disable the block payment on unencrypted website option, everything works correctly.

What could it be, an error in the PayPal option, on my website itself?

SSL certificate on my website appears to be OK, activated correctly.

**Comment by MrMicky-FR** [comment]
Hi, I just tested and it' working fine for me. If you are using Cloudflare with flexible SSL, make sure to install & enable the Cloudflare Support plugin. Otherwise you might try with PayPal Express Checkout, as I don't see how we could modify the integration as the generated URLs are already in https (encrypted) if the website is using HTTPS
