### ISSUE TITLE
Payment method

### ISSUE THREAD

**Issue by Beshudar** [Azuriom/Plugin-Shop#23]
Please add the UnitPay payment method. https://unitpay.ru/

**Comment by MrMicky-FR** [comment]
Hi, thanks for your suggestion :)
Unfortunately it would be too complicated for us to add and test country-specific payment gateways in the shop for every countries.
The best solution would be to create a small plugin to add this payment method, like we did for Dedipass (a french payment gateway) with this plugin: https://github.com/Azuriom/Plugin-DedipassPayment.

**Comment by tapika** [comment]
@MrMicky-FR Would it be possible to re-open this ticket - main problem is that in order to write Azurium Unitpay plugin, you need to have unitpay account for testing, which in a turn requires Russian pass. Even if you're php developer, it's insufficient. I think Azirium as a web interface is not so complex to make, more complex it's to have rich support for different payment methods.

Even commonly used methods, like mastercards or Visa are not supported out of box, not talking about Russian or other payment methods.

**Comment by tapika** [comment]
Btw, search for https://github.com/search?q=registerPaymentMethod&type=Code 
gives hits in quite many different languages, where javascript gives most of hits. I suspect it would be enough to write one Azuriom plugin, which uses some of javascript libraries, which in a turn uses a lot of payment systems. Need to locate right javascript library for this purpose.

**Comment by MrMicky-FR** [comment]
> Even commonly used methods, like mastercards or Visa are not supported out of box

You can’t directly accept credits cards payments on the website, you need to use a third-party service like Stripe (recommended), PayPal, Mollie, … (which are supported)

> Btw, search for https://github.com/search?q=registerPaymentMethod&type=Code
gives hits in quite many different languages, where javascript gives most of hits.

I don’t see any link between this and UnitPay

And for the original question, my answer is the same as above.
