### ISSUE TITLE
Link Shop offers don't work 

### ISSUE THREAD

**Issue by AliasPedroKarim** [Azuriom/Plugin-Shop#40]
When you try to credit an azuriom account with money from the azuriom website via the shop plugin, the following happens:

![PSX_20211124_192645](https://user-images.githubusercontent.com/28218643/143301481-da6a424a-110f-4fd5-862a-061db8cb2a52.jpg)

So I went to the code and I noticed that the `shop/offers/{offer}/{gateway:type}` route in `route/web.php` was POST while on the HTML view, there was a simple link so a GET.

![PSX_20211124_201245](https://user-images.githubusercontent.com/28218643/143303468-99d28f1c-fe8c-4d12-b1d8-f051bd20b5c6.jpg)
![PSX_20211124_201147](https://user-images.githubusercontent.com/28218643/143303495-c4ba00fa-de09-4f70-bb0e-21209ad2fcfa.jpg)
![PSX_20211124_201613](https://user-images.githubusercontent.com/28218643/143303517-16f8e395-5f6a-4eae-bc95-8f87453363e5.jpg)

**Comment by MrMicky-FR** [comment]
Hi,
I’m not sure what’s causing this issue because it’s expected for the route to be in POST, as there is a small script to make requests as POST requests : 
https://github.com/Azuriom/Plugin-Shop/blob/265bbb065104e86f2f1d749ed01cc77a24b1441b/resources/views/offers/select.blade.php#L7-L14
Also using the wrong request method results in a 403 (Method not allowed) and not in a 404 (Not found)

I think the issue is because the offer is not enabled, I will try to take a look when I have some time

**Comment by AliasPedroKarim** [comment]
I checked the offers and everything seems to be correct, they are well activated 
![2021-11-25 18 41 17](https://user-images.githubusercontent.com/28218643/143485687-890e623e-8307-442b-ac19-746b85a8324f.png)
![2021-11-25 18 38 48](https://user-images.githubusercontent.com/28218643/143485824-d07c0203-d50a-4404-b9e0-931039ba2d4f.png)
![2021-11-25 18 47 34](https://user-images.githubusercontent.com/28218643/143485858-287d02ec-9085-4867-9f27-d4564f25039c.png)

**Comment by Fabian-Evolved** [comment]
I noticed the same thing, for me however when someone presses the actual button, it shows a 404 page, however when they click the title it brings them to the Paypal transfer.

Let me show an example: https://i.imgur.com/RKB5WUI.png

This up here is a poor example, because my paint skills are aweful.
But the titles indicated with the RED arrow, work and send people to paypal for the money transfer.
The buttons that are indicated with a RED line through it, throw up a 404 page.

both the Title and the button link to the exact same link which is: "https://www.domain.com/shop/offers/1/paypal"
However not both of these actually work. only the title one does.

I hope i properly explained it, if i didn't please let me know, and i'll record a little clip explaining it in more detail.

**Comment by MrMicky-FR** [comment]
It seems like this issue is related to the Revolution theme. You would need to contact the developer of this theme as we can’t fix this issue if it’s not related to the shop plugin.
