### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by BrayaanPS** [Azuriom/Plugin-Shop#65]
It would be nice if these widgets were added.
- Best donor (This would be reset every month, it would be the total amount of money spent by the user.). 
- Recent purchases (Latest purchases made in the store).

It would be nice if they could be added to this site.
![image](https://user-images.githubusercontent.com/30274810/177014097-370e3220-ad85-403b-85c1-dab63c7b7089.png)
Example widgets:
![image](https://user-images.githubusercontent.com/30274810/177014108-b6fa57da-c429-4a9b-ab2c-01e8f3bb18c8.png)

**Comment by Javdu10** [comment]
Hi @BrayaanPS 

all of this is already possible to do with a theme if you know some PHP. I don’t think these « widgets » will be added by default because there is millions of « this would be nice to have ». Nonetheless we can add an exemple in the documentation to show the process of adding such thing in a theme

**Comment by BrayaanPS** [comment]
Hi, @Javdu10 
I know it can be done, but that it will be integrated by the plugin, as it should be automatic the users that are added to the best donor and recent payments.

**Comment by MrMicky-FR** [comment]
Not really of these widgets, especially the "best donor" one

**Comment by MrMicky-FR** [comment]
Added in c4b88f5cf2f0d9414e2c2c71fe587641938fd327
